#!/usr/bin/env python3

import sys

CONFIG_PATH = "/etc/nixos/config.nix"

def print_help():
    print("nixpm — add/remove packages in configuration.nix like apt install")
    print("Usage:")
    print("    nixpm install <package> [<package> ...]")
    print("    nixpm remove  <package> [<package> ...]")
    print("    nixpm list")
    print("    nixpm search  <term>")

def cmd_install(packages):
    print(f"Installing packages: {packages}")

def cmd_remove(packages):
    print(f"Removing packages: {packages}")

def error_handler(args):
    if len(args) < 2:
        print_help()
        sys.exit(1)

    if args[1] in ("-h", "--help"):
        print_help()
        sys.exit(0)


def main():
    error_handler(sys.argv)

    functions = {
        "install": cmd_install,
        "remove": cmd_remove
    }

    command = sys.argv[1]

    if command not in functions:
        print("Invalid function")
        sys.exit(1)

    functions[command](sys.argv[2:])

if __name__ == "__main__":
    main()